server:
  port: 8888
eureka:
  instance:
    hostname: regserver
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/,http://127.0.0.1:8889/eureka/
spring:
  application:
    name: virgo-register